export const AIRCRAFT_SERVICE = 'AIRCRAFT_SERVICE';
export const ORDER_SERVICE = 'ORDER_SERVICE';
export const RESERVATION_SERVICE = 'RESERVATION_SERVICE';

export const NATS_SERVICE = 'NATS_SERVICE';
